[package]
name = "four-arms"
version = "0.1.2"
edition = "2024"
description = "Crate for using manipulation forward, inverse kinematics and use planner like RRT, RRT*, STOMP, CHOMP, etc."
readme = "../../README.md"
repository = "https://github.com/sachinkum0009/four-arms"
license = "Apache-2.0"
keywords = ["fourarms", "robotics", "manipulatior", "planner"]

[dependencies]
nalgebra = "0.35.0"
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
quick-xml = { version = "0.40.1", features = ["serde", "serialize"] }
thiserror = { version = "2.0.18" }
rand = "0.10.1"
rerun = "0.33.0"
tracing = "0.1.44"

[[example]]
name = "ik_planner"
path = "examples/ik_planner.rs"

[[example]]
name = "rerun_planner"
path = "examples/rerun_planner.rs"

[[example]]
name = "kd_tree_ex"
path = "examples/kd_tree_ex.rs"

[[example]]
name = "dijstra_ex"
path = "examples/dijstra_ex.rs"
